---

- name: Set hostname
  hostname: >
    name={{ hostname }}

- name: Create app directory for the user
  file: >
    path={{ user_directory_apps }}
    state=directory
    owner={{ user }}
    group={{ user }}
    mode=0755

- name: Create app config directory for the user
  file: >
    path={{ user_directory_app_config }}
    state=directory
    owner={{ user }}
    group={{ user }}
    mode=0755
