---

- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo
  strategy: free
  vars:
    # Your timezone
    - timezone: 'Europe/Amsterdam'
    # Your username
    - user: app
    - user_directory_apps: "/home/{{ user }}/apps"
    - user_directory_app_config: "/home/{{ user }}/config/"
    # Set the hostname
    - hostname: tokyo
    # Swapfile
    - swapfile_location: /swapfile
    - swapfile_size: 512MB
    # Nodejs
    - nodejs_install_npm_user: "app"
    - npm_config_prefix: "/usr/local/lib/npm"
    - nodejs_npm_global_packages:
      - name: pm2
    # PHP 7
    - php_ppa: "ppa:ondrej/php"
    - php_packages:
      - php7.1-common
      - php7.1-cli
      - php7.1-intl
      - php7.1-curl
      - php7.1-cgi
      - php7.1-fpm
      - php7.1-mysql
      - php7.1-gd
      - php7.1-mbstring
      - php7.1-mcrypt
      - php7.1-dom
      - php7.1-bcmath
      - php7.1-xml
    - php_timezone: "{{ timezone }}"
    - php_upload_max_filesize: "20M"
    - php_post_max_size: "20M"
    - php_memory_limit: "1024M"
    - php_max_execution_time: 100
    - php_opcache_enable: 0
    - php_opcache_revalidate_freq: 2592000
    - php_opcache_opcache_validate_timestamps: 1
    - php_opcache_max_accelerated_files: 20000
    - php_opcache_memory_consumption: 192
    - php_opcache_interned_strings_buffer: 16
    - php_opcache_fast_shutdown:
    - php_allow_url_fopen: 0
    # MariaDB
    - mariadb_upstream_version: 10.2
    - mariadb_mysqld_root_password: "{{ lookup('password', '~/.ansible/provision/' + hostname + '/db-password chars=ascii_letters') }}"
    - mariadb_mysqld_backup: false
    # Redis
    - redis_bind: 127.0.0.1

  # Check for python
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  roles:
      # - initialize
      # - franklinkim.timezone
      # - f500.locale
      # - hostname
      # - users
      # - git
      - nginx
      # - kamaln7.swapfile
      # - geerlingguy.nodejs
      # - itcraftsmanpl.php7
      # - wp-cli
      # - composer
      # - nickjj.mariadb
      # - DavidWittman.redis
      # - sendmail
