---

- name: Install system wide dependencies
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - curl
    - whois
    - unzip
    - htop
    - software-properties-common
    - ntp
    - xvfb
    - libfontconfig
    - wkhtmltopdf
