---

- name: Update apt repositories
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: Upgrade apt repositories
  apt: >
    upgrade=full

- name: Install unattended-upgrades
  apt: >
    name=unattended-upgrades
    state=present

- include: dependencies.yml

- name: Make sure the right locale is set
  locale_gen: >
    name=en_US.UTF-8
    state=present

- name: Ensure ntp starts on a fresh reboot
  service:
    name: ntp
    state: started
    enabled: yes
