---

- name: Add PHP5.6 ppa
  apt_repository: >
    repo=ppa:ondrej/php5-5.6
    update_cache=yes

- name: Install PHP
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - php5
    - php5-cli
    - php5-fpm

- name: Un comment cgi.fix_pathinfo
  replace: >
    dest=/etc/php5/fpm/php.ini
    regexp=';cgi.fix_pathinfo=1'
    replace='cgi.fix_pathinfo=0'

- include: modules.yml
