---

- name: Install PHP modules
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - php5-curl
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-mcrypt
  notify:
    - Restart php-fpm
    - Restart nginx
